version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: nginx-https
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/j10c102.p.ssafy.io/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/j10c102.p.ssafy.io/privkey.pem:/etc/ssl/private/privkey.pem
    restart: unless-stopped

  back:
    container_name: back
    image: junwon1131/s10c102-back:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - jenkins-network
    environment:
      - USE_PROFILE=prod
      - SPRING_PROFILES_ACTIVE=prod



networks:
  jenkins-network:
    external: true
